disabled_rules:
  - trailing_whitespace
  - todo
opt_in_rules:
  - empty_count
  - closure_end_indentation
line_length: 140
file_length:
  warning: 500
  error: 800
type_body_length:
  warning: 300
  error: 500
force_unwrapping: error
identifier_name:
  min_length: 2
excluded:
  - .build
  - DerivedData
